name: first workflow

on: 
  push:
  workflow_dispatch:

jobs:
  Hello-World:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"

#second job
 echo-goodbye:
  runs-on: ubuntu-slim
  steps:
  - name: say goodbye
    run: echo "Goodbye
  #multiple commands
  - name: Multi-line bash
  run:
   echo: " I am"
   echo: "Multi Line"
   echo: "Script"
